### ISSUE TITLE
✨ Migration - Consulting Pages

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website.Content#3]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw  @tiagov8 

To Myself
  
### Pain
We need to migrate the existing Consulting / Services pages.

### Tasks

- [x] Investigate the existing consulting pages
- [x] Create PBI for all consulting pages based on their categories

Thanks!

**Comment by ozairashfaqueSSW** [comment]
> - [x] Investigate the existing consulting pages
> - [x] Create PBI for all consulting pages based on their categories

Done - Investigated the consulting pages and added PBIs for each issue

- #19 
- #21 
- #22 
- #23 
- #24 
- #25
