### ISSUE TITLE
Subtask - add zendesk solutions component to Zendesk page

### ISSUE THREAD

**Issue by ozairashfaqueSSW** [SSWConsulting/SSW.Website.Content#56]
Cc: @adamcogan @pierssinclairssw @lukecookssw @kevinpho2022 @bigtony97 @paulsmythssw 

To Myself,
  
### Pain

[Zendesk page](https://www.ssw.com.au/ssw/Consulting/Zendesk.aspx) has its own unique template for Zendesk solutions similar to the technologies component.
### Suggested Solution

Follow the same solution that has been implemented for technologies
### Tasks

- [x] Investigate Zendesk Solutions component
- [x] Implement the solution

### More Information

As zendesk solutions has its own unique template, it is advise to create separate root directory for it in [SSW.Website.Content](https://github.com/SSWConsulting/SSW.Website.Content)
### Screenshots

![image](https://user-images.githubusercontent.com/96504411/170385435-462b72e5-9e63-4a9d-bc47-c1902e9047cb.png)
**Figure: Thankyou page on SSW website**

Thanks!

**Comment by bigtony97** [comment]
Done - refactored technologies component to allow most content in body of the mdx and a custom header function in the consulting template - https://github.com/SSWConsulting/SSW.Website/pull/204
